i18n: Event view
we-dance/platform pull request #108
Opened 2022-01-27 17:30 UTC by amanuela97

translation for ref #72 

demo-link [https://wedance-amanuela97.netlify.app/](url)

2022-01-27 19:06 UTC, razbakov requested changes
@amanuela97 please rebase your branch and resolve conflicts

2022-01-27 19:20 UTC, best-lucky1030 reviewed
This is i18n for event view?

2022-01-28 14:38 UTC, razbakov approved these changes

2022-01-28 14:40 UTC, razbakov commented
> This is i18n for event view?

@best-lucky1030 see referenced issue for more details.

2022-01-28 20:09 UTC, merged