i18n: Auth
we-dance/platform pull request #111
Opened 2022-01-28 16:30 UTC by Stefanacef

Closes #73 
[Demo-link](https://wedance-stefanacef.netlify.app/nopassword/)

2022-01-28 19:40 UTC, razbakov commented
@Stefanacef i forced update your auth-translation branch, you will need to delete that branch locally and check it out again.
I had to reset unrelevant changes to avoid conflicts on merge.

2022-01-29 04:52 UTC, best-lucky1030 commented on layouts/default.vue
> +        <div class="p-4">{{ $t('popup.request') }} {{ showAuthPopup }}</div>
Yes, that's correct. it comes from the `title` property.  👍

2022-02-01 09:54 UTC, razbakov commented on layouts/default.vue
> +      :title="$t('popup.title')"
That wasn't updated

2022-02-01 21:19 UTC, razbakov commented
@Stefanacef this pull request doesn't contain your changes.

2022-02-01 21:38 UTC, Stefanacef commented
yes, I'm working on fixing the situation now :)

2022-02-02 06:46 UTC, best-lucky1030 reviewed
I think there will be conflicts when this PR is merged into `main` branch.

2022-02-02 06:47 UTC, best-lucky1030 commented
resolved the conflit on `en.yml file`

2022-02-02 21:27 UTC, razbakov requested changes
Very good! 

One small polishing for translators to better understand the sentence they going to translate.

And one more thing: try to signout and click on different buttons on the Feed:
- star
- watch
- context menu (three dots near post)

They all have different auth message, cuz they have a special `title` attribute on the button.
Find all usage of the `<TButton` in the code and update `title`

2022-02-02 21:27 UTC, razbakov commented on locales/en.yml
> +    body: Sign in to {message}
```suggestion
    body: Sign in to {action}
```

2022-02-02 21:27 UTC, razbakov commented on locales/en.yml
> +  login: Login to {title}
```suggestion
  login: Login to {action}
```

2022-02-03 10:23 UTC, razbakov approved these changes

2022-02-03 10:30 UTC, amanuela97 approved these changes

2022-02-03 11:08 UTC, merged