Homei18n
we-dance/platform pull request #112
Opened 2022-01-28 18:21 UTC by nelson2411

### Changes
* Localization added in Home page
* Keys for localization created in en.yml file

## Demo: 
https://nelson-wedance.netlify.app/

2022-01-28 20:08 UTC, razbakov requested changes
There are still some untranslated strings in the `index.vue`

2022-01-29 00:57 UTC, razbakov approved these changes

2022-01-29 00:57 UTC, merged

2022-01-29 04:54 UTC, best-lucky1030 reviewed
This request already was merged?

2022-01-29 04:56 UTC, razbakov commented
@best-lucky1030 obviously. it says "merged".