Replacing .typo css with typography plugin #127
we-dance/platform pull request #164
Opened 2022-02-08 18:01 UTC by harshbrahmxatriya

I have installed typography plugin and added it in tailwind.config.js file.
And you can test it on the profile page of a user, it should be visible right after the 'Welcome to WeDance!' line.

2022-02-09 06:52 UTC, harshbrahmxatriya commented
> 1. rebase your branch onto beta and make sure your pull request contains only your commits related to this issue
> 
>     2. there more places where class "typo" is used

Actually, I have changed only one to look the change it does, then I will change rest files.

2022-02-09 12:06 UTC, razbakov requested changes

2022-02-09 12:06 UTC, razbakov commented on tailwind.config.js
> +    require('@tailwindcss/typography')
comma is missing
```suggestion
    require('@tailwindcss/typography'),
```

2022-02-10 09:09 UTC, razbakov commented
Looks like deploy preview doesn't have code changes, see [example](https://6203ab6b4f017c00087232ed--wedance-harshbrahmxatriya.netlify.app/about) here is still `typo` class.

2022-02-10 09:27 UTC, razbakov approved these changes

2022-02-10 09:28 UTC, merged