Prettier tailwindcss
we-dance/platform pull request #165
Opened 2022-02-08 20:53 UTC by larrycoal

## What Changed
Integrated prettier-plugin-tailwindcss

## How to use it

Should reformat tailwindcss class on save or run ' npx prettier --write . ' to reformat all files or 'npx prettier --write /file_path' to reformat a particular file

2022-02-08 21:14 UTC, razbakov requested changes
we need also to reformat all the files

2022-02-08 21:14 UTC, razbakov commented on pages/cities.vue
> +        class="hover:bg -red-100 flex-grow cursor-pointer p-4 text-lg"
I guess you added a space here manually

2022-02-08 21:14 UTC, razbakov commented on .prettierrc
> +}
As you see github warns here that there is "no newline at end of file"

2022-02-08 21:53 UTC, razbakov commented on .prettierrc
> +  "tailwindConfig": "./tailwind.config.js"
prettier throws this message:
`Ignored unknown option { tailwindConfig: "./tailwind.config.js" }`

2022-02-08 21:59 UTC, razbakov approved these changes
i fixed it, merging now

2022-02-08 21:59 UTC, merged

2022-02-09 04:20 UTC, best-lucky1030 reviewed
All of prettier syntax are working?
Seeing the changed code, most of them are replaced classname and single quoted.

2022-02-09 09:13 UTC, razbakov commented
@best-lucky1030 did you see the linked issue?