uninstalled redundant dependency and fixed a build error
we-dance/platform pull request #23
Opened 2021-07-26 14:59 UTC by larrycoal

2021-07-26 15:00 UTC, razbakov requested changes

2021-07-26 15:00 UTC, razbakov commented on .env.example
> +FIREBASE_ANALYTICS_ENABLED=
please ensure there is always a new line in the end of the file

2021-07-26 15:21 UTC, larrycoal commented
changes made

2021-07-26 22:41 UTC, razbakov approved these changes

2021-07-27 08:30 UTC, razbakov commented
node-sass is required somewhere in build command:

```
10:24:03 AM: $ yarn build
10:24:04 AM: yarn run v1.22.4
10:24:04 AM: $ nuxt build
10:25:43 AM: [fatal] Nuxt build error
10:25:43 AM:   ERROR in ./assets/css/vendors.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/css/vendors.scss)
10:25:43 AM:   Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
10:25:43 AM:   Error: Cannot find module 'node-sass'
```

Full build logs available here - https://app.netlify.com/sites/wedance/deploys/60fed131994ac80007db911f

2021-07-29 09:15 UTC, razbakov requested changes
Please split into 3 pull requests

2021-07-29 10:34 UTC, closed without merging