[sc-427] Artists & Profiles Bio List
we-dance/platform pull request #66
Opened 2021-12-25 16:42 UTC by booleanrecep

### User is able to see bio card of artists/profiles in drop-down list and able to select,edit,delete.
#### Step to follow:
* Go to your profile
* Click  **My Profile** tab
* Click **Add event** button
##### Demo:
![sc-427](https://user-images.githubusercontent.com/36863863/147389485-e0c9b9d8-da3d-446b-a62f-08cd9a69b398.gif)

2021-12-25 18:17 UTC, best-lucky1030 reviewed
Typo.

2021-12-25 18:17 UTC, best-lucky1030 commented on components/TProfileSelect/TBioCard.vue
> +            alt="profil"
this is typo.
not `profil`, it's `profile`.

2021-12-27 17:36 UTC, razbakov commented
@booleanrecep please deploy demo on netlify and provide link, so that we can test

2021-12-29 14:57 UTC, razbakov commented
@booleanrecep great work! 

Now let's replace hardcoded array of profiles with actual profiles. You can reuse the code of /search page for that. It's using Algolia search.

2021-12-30 20:04 UTC, razbakov commented
Nice!

Few changes:

- After adding profile - input should be cleared.
- List should be displayed completely without vertical scroll

And the next thing to do:

- edit bio and role

2022-01-07 14:49 UTC, razbakov commented
@booleanrecep please re-use existing TPopup component

2022-01-07 20:28 UTC, razbakov commented
@booleanrecep it should not be possible to add the same profile multiple times

2022-01-08 16:46 UTC, razbakov commented
@booleanrecep it's not possible to save role

2022-01-14 08:19 UTC, best-lucky1030 reviewed
looks good.

2022-01-14 10:07 UTC, razbakov commented
Changes:
- rename field to "Guests"
- place after Description
- use label position "top"

2022-01-14 10:07 UTC, razbakov requested changes
Changes:
- rename field to "Team"
- place after Description
- use label position "top"

2022-01-24 18:41 UTC, closed without merging